[package]
name = "node-rpc"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node rpc methods."
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["server"] }
node-primitives = { version = "2.0.0", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
pallet-transaction-payment-rpc = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
mmr-rpc = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-chain-spec = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-client-api = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-consensus-babe = { version = "0.10.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-consensus-babe-rpc = { version = "0.10.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-consensus-grandpa = { version = "0.10.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-consensus-grandpa-rpc = { version = "0.10.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-rpc = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-rpc-api = { version = "0.10.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-rpc-spec-v2 = { version = "0.10.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-sync-state-rpc = { version = "0.10.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sc-transaction-pool-api = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sp-api = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sp-block-builder = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sp-blockchain = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sp-consensus = { version = "0.10.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sp-consensus-babe = { version = "0.10.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sp-keystore = { version = "0.13.0", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
sp-runtime = { version = "7.0.0", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
substrate-frame-rpc-system = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
substrate-state-trie-migration-rpc = { version = "4.0.0-dev", branch = "polkadot-v0.9.43", git = "https://github.com/paritytech/substrate" }
