[package]
name = "liberland-gen"
version = "0.1.0"
edition = "2021"

[build-dependencies]
kitchensink-runtime = { path = "../bin/node/runtime" }
sp-core = { tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk", default-features = false }

[features]
default = []
