name: test solidity contracts

on:
  push:
    paths:
      - 'substrate/eth-bridge/contracts/**'
  pull_request:
    paths:
      - 'substrate/eth-bridge/contracts/**'

env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    strategy:
      fail-fast: true

    name: Solhint linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v3
      
      - name: Install solhint
        run: npm install -g solhint

      - name: Run solhint
        working-directory: ./substrate/eth-bridge/contracts/
        run: solhint 'src/**/*.sol'

  build_and_test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        working-directory: ./substrate/eth-bridge/contracts/
        run: |
          forge --version
          forge build --build-info --sizes
        id: build_solidity

      - name: Run Forge tests
        working-directory: ./substrate/eth-bridge/contracts/
        run: |
          forge test -vvv
        id: test_solidity

      - name: Run Forge fmt check
        working-directory: ./substrate/eth-bridge/contracts/
        run: |
          forge fmt --check
        id: fmt_solidity

      - name: Analyze with Slither
        uses: crytic/slither-action@v0.3.0
        with:
          target: ./substrate/eth-bridge/contracts/
          slither-config: ./substrate/eth-bridge/contracts/slither.config.json
          ignore-compile: true
